#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${PUBSUB_PROJECT_ID}" ]]; then
  echo "Missing PUBSUB_PROJECT_ID environment variable" >&2
  exit 1
fi

# Config gcloud project
gcloud config set project ${PUBSUB_PROJECT_ID}

# Start emulator
gcloud beta emulators pubsub start \
  --data-dir=/opt/data \
  --host-port=0.0.0.0:8085