#!/usr/bin/env bash

if [[ $* == *--push* ]] ; then

    for dir in */ ; do

        image=`basename "$dir"`

        echo Building and pushing image \"hyperlabbe/$image\"

        docker buildx build --platform linux/amd64,linux/arm64 --tag hyperlabbe/$image --push ./$dir

    done

else

    for dir in */ ; do

        image=`basename "$dir"`

        echo Building image \"hyperlabbe/$image\"

        docker build --tag hyperlabbe/$image ./$dir

    done

fi
